# Generated by Django 5.1.4 on 2024-12-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_rename_copies_book_current_copies_book_total_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_copies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(),
        ),
    ]
